# Generated by Django 6.0 on 2026-04-22 02:09

import mediafiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.CharField(default=mediafiles.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=mediafiles.models.upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
