# Generated by Django 6.0 on 2026-04-21 07:58

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True)),
                ('action_title', models.CharField(blank=True, max_length=100)),
                ('gradient_type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'banners',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(blank=True, max_length=255)),
                ('banner_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('sales', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('banner', 'Banner轮播'), ('categories', '分类导航'), ('flashSale', '限时秒杀'), ('hotRank', '热销榜单'), ('recommend', '为你推荐'), ('newArrival', '新品上市'), ('promotion', '优惠活动')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('type', models.CharField(choices=[('logistics', '物流通知'), ('order', '订单提醒'), ('promo', '优惠活动'), ('sys', '系统通知')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('action', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('store', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', '待支付'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.IntegerField(default=0)),
                ('sales_count', models.IntegerField(default=0)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('threshold', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_coupons',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('spec', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.order')),
            ],
            options={
                'db_table': 'order_products',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='backend.product')),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('shop_logo', models.CharField(blank=True, max_length=255)),
                ('images', models.JSONField(default=list)),
                ('detail_images', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('is_selected', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('user_avatar', models.CharField(blank=True, max_length=255)),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('spec', models.CharField(blank=True, max_length=255)),
                ('images', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.product')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='backend.product')),
            ],
            options={
                'db_table': 'skus',
            },
        ),
        migrations.CreateModel(
            name='SpecGroup',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='backend.product')),
            ],
            options={
                'db_table': 'spec_groups',
            },
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='backend.specgroup')),
            ],
            options={
                'db_table': 'spec_values',
            },
        ),
        migrations.CreateModel(
            name='SKUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sku')),
                ('spec_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.specvalue')),
            ],
            options={
                'db_table': 'sku_specs',
                'unique_together': {('sku', 'spec_value')},
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='spec_values',
            field=models.ManyToManyField(related_name='skus', through='backend.SKUSpec', to='backend.specvalue'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='backend.category')),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
    ]
