# Generated by Django 6.0.4 on 2026-04-23 15:04

import backend.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediafiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.IntegerField(default=0)),
                ('sales_count', models.IntegerField(default=0)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_banners', to='mediafiles.mediafile')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_icons', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales', models.CharField(blank=True, max_length=50)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_images', to='mediafiles.mediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.CharField(max_length=100)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_images', to='mediafiles.mediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True)),
                ('action_title', models.CharField(blank=True, max_length=100)),
                ('gradient_type', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_banners', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'home_banners',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomePromotion',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_promotions', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'home_promotions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('logistics', '物流通知'), ('order', '订单提醒'), ('promo', '优惠活动'), ('sys', '系统通知')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('action', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('store', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '待发货'), ('shipped', '待收货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, help_text='实付金额', max_digits=10, null=True)),
                ('freight', models.DecimalField(decimal_places=2, default=0, help_text='运费', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='优惠金额', max_digits=10)),
                ('address_name', models.CharField(blank=True, max_length=100)),
                ('address_phone', models.CharField(blank=True, max_length=50)),
                ('address_province', models.CharField(blank=True, max_length=100)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_district', models.CharField(blank=True, max_length=100)),
                ('address_detail', models.TextField(blank=True)),
                ('pay_time', models.DateTimeField(blank=True, help_text='支付时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('spec', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediafiles.mediafile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.order')),
            ],
            options={
                'db_table': 'order_products',
            },
        ),
        migrations.CreateModel(
            name='HomeRecommend',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='recommend_sections', to='backend.product')),
            ],
            options={
                'db_table': 'home_recommends',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeNewArrival',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='new_arrival_sections', to='backend.product')),
            ],
            options={
                'db_table': 'home_new_arrivals',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeHotRank',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='hot_rank_sections', to='backend.product')),
            ],
            options={
                'db_table': 'home_hot_ranks',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFlashSale',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='flash_sale_sections', to='backend.product')),
            ],
            options={
                'db_table': 'home_flash_sales',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('is_selected', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('spec', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, related_name='review_images', to='mediafiles.mediafile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('user_avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_avatars', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediafiles.mediafile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='backend.product')),
            ],
            options={
                'db_table': 'skus',
            },
        ),
        migrations.CreateModel(
            name='SpecGroup',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='backend.product')),
            ],
            options={
                'db_table': 'spec_groups',
            },
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='backend.specgroup')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'spec_values',
            },
        ),
        migrations.CreateModel(
            name='SKUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sku')),
                ('spec_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.specvalue')),
            ],
            options={
                'db_table': 'sku_specs',
                'unique_together': {('sku', 'spec_value')},
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='spec_values',
            field=models.ManyToManyField(related_name='skus', through='backend.SKUSpec', to='backend.specvalue'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='backend.category')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_icons', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'subcategories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend.subcategory'),
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('threshold', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('time', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_coupons',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', '管理员'), ('user', '普通用户')], default='user', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('follow_count', models.IntegerField(default=0)),
                ('fans_count', models.IntegerField(default=0)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatars', to='mediafiles.mediafile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='backend.product')),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('detail_images', models.ManyToManyField(blank=True, related_name='product_detail_extras', to='mediafiles.mediafile')),
                ('images', models.ManyToManyField(blank=True, related_name='product_detail_images', to='mediafiles.mediafile')),
                ('shop_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_logos', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
    ]
