# Generated by Django 6.0 on 2026-04-21 08:47

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specgroup',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specvalue',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
    ]
