# Generated by Django 6.0 on 2026-05-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
