# Generated by Django 6.0 on 2026-04-21 09:29

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_banner_id_alter_cartitem_id_alter_favorite_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
    ]
