# Generated by Django 6.0 on 2026-05-29 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_add_favorite_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='潮流优品官方旗舰店', max_length=100)),
                ('description', models.TextField(blank=True, default='专注时尚潮流，只卖好货')),
                ('score', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('product_count', models.IntegerField(default=0)),
                ('sales', models.CharField(blank=True, default='12.8万', max_length=20)),
                ('fans_count', models.CharField(blank=True, default='56.2万', max_length=20)),
            ],
            options={
                'db_table': 'shop_info',
            },
        ),
        migrations.CreateModel(
            name='VIPMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('none', '普通会员'), ('bronze', '铜牌会员'), ('silver', '银牌会员'), ('gold', '黄金会员'), ('diamond', '钻石会员')], default='none', max_length=20)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('growth_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vip_memberships',
            },
        ),
    ]
