# Generated by Django 6.0 on 2026-04-22 07:46

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_mediafile_refs'),
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True)),
                ('action_title', models.CharField(blank=True, max_length=100)),
                ('gradient_type', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_banners', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'home_banners',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFlashSale',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_flash_sales',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeHotRank',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_hot_ranks',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeNewArrival',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_new_arrivals',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomePromotion',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_promotions', to='mediafiles.mediafile')),
            ],
            options={
                'db_table': 'home_promotions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeRecommend',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_recommends',
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.DeleteModel(
            name='HomeSection',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend.subcategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_icons', to='mediafiles.mediafile'),
        ),
        migrations.AddField(
            model_name='homeflashsale',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='flash_sale_sections', to='backend.product'),
        ),
        migrations.AddField(
            model_name='homehotrank',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='hot_rank_sections', to='backend.product'),
        ),
        migrations.AddField(
            model_name='homenewarrival',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='new_arrival_sections', to='backend.product'),
        ),
        migrations.AddField(
            model_name='homerecommend',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='recommend_sections', to='backend.product'),
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
