# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_add_shop_and_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
