# Generated by Codex on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_orderproduct_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cart_items',
                to='backend.sku',
            ),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='status',
            field=models.CharField(
                choices=[('available', '可用'), ('used', '已使用'), ('expired', '已过期')],
                default='available',
                max_length=20,
            ),
        ),
    ]
