# Generated by Django 6.0.4 on 2026-04-23 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_add_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_id',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='backend.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='优惠金额', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='运费', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, help_text='支付时间', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='实付金额', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '待发货'), ('shipped', '待收货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=50),
        ),
    ]
