# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_cartitem_sku_usercoupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(
                choices=[('male', '男'), ('female', '女'), ('secret', '保密')],
                default='secret',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
