# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_userprofile_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='发货时间', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, help_text='物流承运商', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='物流单号', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='after_sale_status',
            field=models.CharField(
                choices=[
                    ('none', '未申请'),
                    ('requested', '已申请'),
                    ('processing', '处理中'),
                    ('refunded', '已退款'),
                    ('rejected', '已拒绝'),
                ],
                default='none',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='after_sale_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='after_sale_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
