# Generated by Django 4.2.30 on 2026-07-25 13:59

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0009_browsehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('wxpay', '微信支付'), ('alipay', '支付宝'), ('balance', '余额支付'), ('sandbox', '沙箱支付')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CNY', max_length=10)),
                ('status', models.CharField(choices=[('created', '已创建'), ('requires_action', '待用户操作'), ('processing', '处理中'), ('succeeded', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消'), ('expired', '已过期')], default='created', max_length=30)),
                ('payment_url', models.URLField(blank=True)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='backend.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payment_tra_user_id_131e27_idx'), models.Index(fields=['order', 'status'], name='payment_tra_order_i_650087_idx'), models.Index(fields=['provider_transaction_id'], name='payment_tra_provide_10d447_idx')],
            },
        ),
    ]
