# Generated by Django 4.2.30 on 2026-07-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='landing_badge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='landing_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='landing_subtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='banner_landings', to='backend.product'),
        ),
    ]
